name: Code Quality

on:
  pull_request:
    branches: [ mainline, feature_* ]
  workflow_call:
    inputs:
      branch:
        required: false
        type: string

jobs:
  UnitTest:
    name: Unit Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']
    uses: aws-deadline/.github/.github/workflows/reusable_python_build.yml@mainline
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  IntegrationTests:
    name: Integration Tests
    needs: UnitTest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      run: |
        pip install --upgrade hatch

    - name: Run Integration Tests
      run: hatch run integ-test
