name: Mainline Canary

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  IntegrationTests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      run: |
        pip install --upgrade hatch

    - name: Run Integration Tests
      run: hatch run integ-test
      
  MainlineLinuxE2ECanary:
    name: Mainline Linux Canary
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_canary.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      branch: mainline
      environment: canary
      os: linux
    concurrency:
      group: mainlinelinuxe2ecanary

  MainlineWindowsE2ECanary:
    name: Mainline Windows Canary
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_canary.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      branch: mainline
      environment: canary
      os: windows
    concurrency:
      group: mainlinewindowse2ecanary